# Generated by Django 5.1.7 on 2025-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/assets/images/no_user.jpg', upload_to='avatars/'),
        ),
    ]
