# Generated by Django 5.1.7 on 2025-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
