# Generated by Django 5.1.7 on 2025-05-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_member_vehicle_color_member_vehicle_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(default='static/assets/images/no_user.jpg', upload_to='admin_photos/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='static/assets/images/no_user.jpg', upload_to='member_photos/'),
        ),
    ]
