# Generated by Django 5.1.7 on 2025-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('member_created', 'Member Created'), ('message_submitted', 'Message Submitted'), ('member_deleted', 'Member Deleted'), ('user_deleted', 'User Deleted'), ('user_password_changed', 'User Password Changed'), ('member_password_changed', 'Member Password Changed'), ('emergency_alert', 'Emergency Alert')], max_length=50),
        ),
    ]
